language: c

git:
  depth: 5

addons:
  apt:
    packages:
      - libssl-dev
      - python
      - valgrind
      - lcov
      - doxygen
      - graphviz
      - indent
  homebrew:
    packages:
      - openssl
      - doxygen
      - findent
    update: true

jobs:
  include:
    - os: linux
      name: GCC on Linux, Amd64
      compiler: gcc
      arch: amd64
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: Clang on Linux, Amd64
      compiler: clang
      arch: amd64
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: osx
      name: Clang on OS X, Amd64
      compiler: clang
      arch: amd64
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: UBsan, GCC on Linux, Amd64
      compiler: gcc
      arch: amd64
      dist: bionic
      env: UBSAN=true
    - os: linux
      name: UBsan, Clang on Linux, Amd64
      compiler: clang
      arch: amd64
      dist: bionic
      env: UBSAN=true
    - os: linux
      name: Asan, GCC on Linux, Amd64
      compiler: gcc
      arch: amd64
      dist: bionic
      env: ASAN=true
    - os: linux
      name: Asan, Clang on Linux, Amd64
      compiler: clang
      arch: amd64
      dist: bionic
      env: ASAN=true
    - os: linux
      name: GCC on Linux, Aarch64
      compiler: gcc
      arch: arm64
      dist: bionic
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: Clang on Linux, Aarch64
      compiler: clang
      arch: arm64
      dist: bionic
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: GCC on Linux, PowerPC64
      compiler: gcc
      arch: ppc64le
      dist: bionic
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: Clang on Linux, PowerPC64
      compiler: clang
      arch: ppc64le
      dist: bionic
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: GCC on Linux, s390x
      compiler: gcc
      arch: s390x
      dist: bionic
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      name: Clang on Linux, s390x
      compiler: clang
      arch: s390x
      dist: bionic
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: osx
      osx_image: xcode10.1
      name: iPhoneOS, armv7, iOS
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=armv7-apple-ios
        - OPENSSL_HOST=ios-cross
        - IOS_CPU=armv7s
        - IOS_SDK=iPhoneOS
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: iPhoneOS, arm64, iOS
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=aarch64-apple-ios
        - OPENSSL_HOST=ios64-cross
        - IOS_CPU=arm64
        - IOS_SDK=iPhoneOS
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: AppleTVOS, arm64, iOS
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=aarch64-apple-ios
        - OPENSSL_HOST=ios64-cross
        - IOS_CPU=arm64
        - IOS_SDK=AppleTVOS
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: WatchOS, armv7, iOS
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=armv7-apple-ios
        - OPENSSL_HOST=ios-cross
        - IOS_CPU=armv7k
        - IOS_SDK=WatchOS
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: iPhoneSimulator, i386, OS X
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=i386-apple-ios
        - OPENSSL_HOST=iphoneos-cross
        - IOS_CPU=i386
        - IOS_SDK=iPhoneSimulator
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: iPhoneSimulator, x86_64, OS X
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=x86_64-apple-ios
        - OPENSSL_HOST=iphoneos-cross
        - IOS_CPU=x86_64
        - IOS_SDK=iPhoneSimulator
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: AppleTVSimulator, x86_64, OS X
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=x86_64-apple-ios
        - OPENSSL_HOST=iphoneos-cross
        - IOS_CPU=x86_64
        - IOS_SDK=AppleTVSimulator
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: osx
      osx_image: xcode10.1
      name: WatchSimulator, i386, OS X
      arch: amd64
      env:
        - IOS=yes
        - AUTOTOOLS_HOST=i386-apple-ios
        - OPENSSL_HOST=iphoneos-cross
        - IOS_CPU=i386
        - IOS_SDK=WatchSimulator
        - IOS_PREFIX="$HOME/$IOS_SDK-$IOS_CPU"
    - os: linux
      name: Android armv7a, Linux, Amd64
      compiler: clang
      arch: amd64
      dist: bionic
      env:
        - ANDROID=yes
        - AUTOTOOLS_HOST=armv7a-linux-androideabi
        - OPENSSL_HOST=android-arm
        - ANDROID_CPU=armv7a
        - ANDROID_API=23
        - ANDROID_PREFIX="$HOME/android$ANDROID_API-$ANDROID_CPU"
        - ANDROID_SDK_ROOT="$HOME/android-sdk"
        - ANDROID_NDK_ROOT="$HOME/android-ndk"
    - os: linux
      name: Android aarch64, Linux, Amd64
      compiler: clang
      arch: amd64
      dist: bionic
      env:
        - ANDROID=yes
        - AUTOTOOLS_HOST=aarch64-linux-android
        - OPENSSL_HOST=android-arm64
        - ANDROID_CPU=aarch64
        - ANDROID_API=23
        - ANDROID_PREFIX="$HOME/android$ANDROID_API-$ANDROID_CPU"
        - ANDROID_SDK_ROOT="$HOME/android-sdk"
        - ANDROID_NDK_ROOT="$HOME/android-ndk"
    - os: linux
      name: Android x86, Linux, Amd64
      compiler: clang
      arch: amd64
      dist: bionic
      env:
        - ANDROID=yes
        - AUTOTOOLS_HOST=i686-linux-android
        - OPENSSL_HOST=android-x86
        - ANDROID_CPU=x86
        - ANDROID_API=23
        - ANDROID_PREFIX="$HOME/android$ANDROID_API-$ANDROID_CPU"
        - ANDROID_SDK_ROOT="$HOME/android-sdk"
        - ANDROID_NDK_ROOT="$HOME/android-ndk"
    - os: linux
      name: Android x86_64, Linux, Amd64
      compiler: clang
      arch: amd64
      dist: bionic
      env:
        - ANDROID=yes
        - AUTOTOOLS_HOST=x86_64-linux-android
        - OPENSSL_HOST=android-x86_64
        - ANDROID_CPU=x86_64
        - ANDROID_API=23
        - ANDROID_PREFIX="$HOME/android$ANDROID_API-$ANDROID_CPU"
        - ANDROID_SDK_ROOT="$HOME/android-sdk"
        - ANDROID_NDK_ROOT="$HOME/android-ndk"

before_script:
  - |
    if [ "$ANDROID" = "yes" ]; then
      ./contrib/android/install_tools.sh
    elif [ "$IOS" = "yes" ]; then
      ./contrib/ios/install_tools.sh
    fi

script:
  - |
    if [ "$UBSAN" = "true" ]; then
      export CFLAGS="-DNDEBUG -g2 -O3 -fsanitize=undefined -fno-sanitize-recover"
      ./test/test_ci.sh
    elif [ "$ASAN" = "true" ]; then
      export CFLAGS="-DNDEBUG -g2 -O3 -fsanitize=address"
      ./test/test_ci.sh
    elif [ "$IOS" = "yes" ]; then
      export AUTOTOOLS_BUILD="$(./config.guess)"
      export PKG_CONFIG_PATH="$IOS_PREFIX/lib/pkgconfig"
      source ./contrib/ios/setenv_ios.sh
      ./contrib/ios/install_openssl.sh
      ./contrib/ios/bootstrap_ldns.sh
      ./configure \
        --build="$AUTOTOOLS_BUILD" --host="$AUTOTOOLS_HOST" \
        --prefix="$IOS_PREFIX" \
        --with-ssl="$IOS_PREFIX" --disable-gost \
        --with-drill --with-examples
      make -j 2
      make install
    elif [ "$ANDROID" = "yes" ]; then
      export AUTOTOOLS_BUILD="$(./config.guess)"
      export PKG_CONFIG_PATH="$ANDROID_PREFIX/lib/pkgconfig"
      ./contrib/android/install_ndk.sh
      source ./contrib/android/setenv_android.sh
      ./contrib/android/install_openssl.sh
      ./contrib/android/bootstrap_ldns.sh
      ./configure \
        --build="$AUTOTOOLS_BUILD" --host="$AUTOTOOLS_HOST" \
        --prefix="$ANDROID_PREFIX" \
        --with-ssl="$ANDROID_PREFIX" --disable-gost \
        --with-drill --with-examples
      make -j 2
      make install
    else
      # Default case for most tests
      ./test/test_ci.sh
    fi
