#!/usr/bin/perl

# Doxygen is usefull for html documentation, but sucks 
# in making manual pages. Still tool also parses the .h
# files with the doxygen documentation and creates
# the man page we want
#
# 2 way process
# 1. All the .h files are processed to create in file in which:
# filename | API | description | return values
# are documented
# 2. Another file is parsed which states which function should
# be grouped together in which manpage. Symlinks are also created.
#
# With this all in place, all documentation should be autogenerated
# from the doxydoc.

use Getopt::Std;

my $state;
my $description;
my $key;
my $return;
my $param;
my $api;

my %description;
my %api;
my %return;
my %options;
my %manpages;

my $MAN_SECTION = "3";
my $MAN_HEADER = ".TH \"ldns \-  a generic DNS(SEC) library\" \"25 Apr 2005\"\n";
my $MAN_FOOTER = ".SH AUTHOR
The ldns team at NLnet Labs. Which consists out of: Jelte Jansen, Erik
Rozendaal and Miek Gieben.

.SH REPORTING BUGS
Please report bugs to ldns-team\@nlnetlabs.nl

.SH BUGS
None sofar. This software just works great.

.SH COPYRIGHT
Copyright (c) 2004, 2005 NLnet Labs.
Licensed under the GPL 2. There is NO warranty; not even for
MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

.SH SEE ALSO
\\fBperldoc Net::DNS\\fR, \\fBRFC1043\\fR,
\\fBRFC1035\\fR, \\fBRFC4033\\fR, \\fBRFC4034\\fR, \\fBRFC4035\\fR.
";



getopts("m:",\%options);
# if -m manpage file is given process that file
# parse the file which tells us what manpages go together
if (defined $options{'m'}) {
	# process
	open(MAN, "<$options{'m'}") or die "Cannot open $options{'m'}";
		# it's line based
		while(<MAN>) {
			chomp;
			if (/^#/) { next; }
			if (/^$/) { next; }
			my @funcs = split /,/, $_;
			$manpages{$funcs[0]} = \@funcs;
			#print "[", $funcs[0], "]\n";
		}
	close(MAN);
} else {
	print "Need -m file to process the .h files\n";
	exit 1;
}

# 0 - somewhere in the file
# 1 - in a doxygen par

$state = 0;
while(<>) {
	chomp;
	if (/\/\*\*/) {
		# /** Seen
		$state = 1;
		next;
	}
	if (/\*\//) {
		$state = 0;
		next;
	}

	if ($state == 1) {
		# inside doxygen 
		s/^[ \t]*\*[ \t]*//;
		
		$description = $description . "\n.br\n" . $_;
	}
	if (/(.*)[\t ]+(.*?)\((.*)\);/) {
		# this should also end the current comment parsing
		$return = $1;
		$key = $2;
		$api = $3;
		# sometimes the * is stuck to the function
		# name instead to the return type
		if ($key =~ /^\*/) {
			#print"Name starts with *\n";
			$key =~ s/^\*//;
			$return = '*' . $return;
		}
		#print "$key\n";
		$description =~ s/\\param\[in\][ \t]//g;
		$description =~ s/\\//g;
		
		$description{$key} = $description;
		$api{$key} = $api;
		$return{$key} = $return;
		undef $description;
		$state = 0;
	}
}

# create the manpages

foreach (keys %manpages) {
	$a = $manpages{$_};

	$filename = @$a[0];

	print $MAN_HEADER;

	print ".SH NAME\n";
	print join ", ", @$a;
	print "\n\n";
	
	print ".SH SYNOPSIS\n";
	print "#include <ldns/ldns.h>\n";
	print ".PP\n";
	foreach $function (@$a) {
		print $return{$function}, " ", $function;
		print "(", $api{$function},");\n";
		print ".PP\n";
	}
	print "\n.SH DESCRIPTION\n";
	foreach $function (@$a) {
		print "\\fI", $function, "\\fR", ":"; 
		print $description{$function};
		print "\n.PP\n";
	}
	print $MAN_FOOTER;
}
