.TH ldns-signzone 1 "30 May 2005"
.SH NAME
ldns-signzone \- sign a zonefile with DNSSEC data
.SH SYNOPSIS
.B ldns-signzone 
[
.IR OPTIONS
]
.IR ZONEFILE 
.IR
KEY 
[KEY 
[KEY] ...
]

.SH DESCRIPTION

\fBldns-signzone\fR is used to generate a DNSSEC signed zone. When run it
will create a new zonefile that contains RRSIG and NSEC resource records, as
specified in RFC 4033, RFC 4034 and RFC 4035. It will add the DNSKEY(s)
that is/are used to sign the zone.

Keys must be specified by their base name (i.e. without .key and .private)
and both the public and private key must be present in the specified
location. Multiple keys can be specified.

.SH OPTIONS
.TP
\fB-e\fR \fIdate\fR
Set expiration date of the signatures to this date, the format can be
YYYYMMDD[hhmmss], or a timestamp.

.TP
\fB-f\fR \fIfile\fR
Use this file to store the signed zone in (default <originalfile>.signed)

.TP
\fB-i\fR \fIdate\fR
Set inception date of the signatures to this date, the format can be
YYYYMMDD[hhmmss], or a timestamp.

.TP
\fB-l\fR
Leave old DNSSEC RRSIGS and NSEC records intact (by default, they are removed from the zone)

.TP
\fB-o\fR \fIorigin\fR
Use this as the origin of the zone, if it cannot be read from the zonefile

.TP
\fB-v\fR
Print the version and exit

.TP
\fB-E\fR \fIname\fR
Use the EVP cryptographic engine with the given name for signing. This can have some extra options; see ENGINE OPTIONS for more information.


.TP
\fB-k\fR \fIid,int\fR
Use the key with the given id as the signing key for algorithm int as a Zone signing key.

.TP
\fB-K\fR \fIid,int\fR
Use the key with the given id as the signing key for algorithm int as a Key signing key.


.SH AUTHOR
Written by the ldns team as an example for ldns usage.

.SH REPORTING BUGS
Report bugs to <ldns-team@nlnetlabs.nl>. 

.SH COPYRIGHT
Copyright (C) 2005 NLnet Labs. This is free software. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
